export const ADDITIONAL_KNOWLEDGE_ARTICLES = {
  "/kennisbank/juiste-verpakking-kiezen": {
    title: "Juiste verpakking kiezen: zo voorkom je schade én bespaar je op verzendkosten",
    seoTitle: "Juiste verpakking kiezen voor pakketten | Sendwise",
    description: "Kies de juiste verzendverpakking, voorkom schade en beperk formaat- en gewichtstoeslagen. Met praktische tips voor dozen, opvulling en meten.",
    excerpt: "Een passende, stevige verpakking beschermt je product en voorkomt dat formaat, gewicht of handmatige verwerking je zending onnodig duur maakt.",
    type: "Handleiding", category: "Verpakking", readTime: "± 7 min", publishedTime: "2026-08-18",
    image: "/kennisbank-piekdrukte.jpg", imageAlt: "Passende verzenddozen voor verschillende pakketformaten",
    quickAnswer: "Kies de kleinste stevige buitenverpakking waarin het product rondom voldoende beschermd is. Meet de gesloten buitenmaat en het werkelijke gewicht, want vervoerders kunnen toeslagen of volumetrisch gewicht toepassen. Vertrouw niet op een ‘breekbaar’-sticker: een verpakking moet zelfstandig tegen sortering, stapeling en stoten kunnen.",
    introTitle: "Verpakking bepaalt bescherming én verwerkbaarheid", introEyebrow: "Minder lucht, minder risico",
    intro: [
      "Een te grote doos vervoert lucht, vraagt extra vulmateriaal en kan bij diensten met volumetrisch gewicht of formaatstaffels duurder uitvallen. Een te krappe of slappe doos vergroot juist de kans op schade.",
      "De vervoerder kijkt naar de gesloten buitenmaat, inclusief uitstekende delen. Meet daarom de verzendklare doos en controleer de actuele limieten van de gekozen dienst.",
    ],
    sections: [
      { id: "kiezen", eyebrow: "Passend bij je product", title: "Waar een goede verpakking aan voldoet", items: [
        { title: "Juiste maat", text: "Beperk lege ruimte, maar houd genoeg plaats voor bescherming rondom kwetsbare delen." },
        { title: "Voldoende sterkte", text: "Stem kartonkwaliteit, bodem en sluiting af op gewicht, vorm en kwetsbaarheid." },
        { title: "Interne bescherming", text: "Voorkom beweging en direct contact met de buitenwand met passend vul- of schokmateriaal." },
        { title: "Sorteerbare vorm", text: "Gebruik bij voorkeur een gesloten rechthoekige doos zonder losse banden, uitstekende randen of ronde vorm." },
      ]},
      { id: "markeringen", eyebrow: "Geen vervanging voor bescherming", title: "Wees voorzichtig met behandelingsstickers", paragraphs: [
        "Een sticker met ‘breekbaar’ of ‘deze zijde boven’ is geen garantie op aparte behandeling. PostNL noemt zulke stickers zelfs als reden voor handmatige verwerking en een mogelijke toeslag.",
        "Verpak daarom alsof het pakket automatisch wordt gesorteerd, gestapeld en mechanisch verplaatst. Gebruik alleen aanvullende markeringen wanneer de productvoorwaarden dat voorschrijven.",
      ]},
      { id: "optimaliseren", eyebrow: "Structureel verbeteren", title: "Optimaliseer op basis van echte zendingen", steps: [
        "Meet de gesloten buitenmaat en het gewicht van je meest voorkomende orders.",
        "Koppel elk product of combinatie aan een passende standaarddoos.",
        "Analyseer formaatcorrecties, schades en vulmateriaal per verpakkingsvariant.",
        "Overweeg dozen op maat wanneer volume en besparing de investering rechtvaardigen.",
      ]},
    ],
    sendwise: "Sendwise helpt je verzendprofiel en vervoerdersvoorwaarden naast elkaar te zetten. Zo zie je waar een kleinere of anders gevormde verpakking toeslagen kan voorkomen, terwijl de inkoop van verpakkingsmateriaal bij je eigen webshop blijft.",
    summary: "Meet de verzendklare buitenmaat, kies een stevige doos met passende interne bescherming en controleer de dienstlimieten. Behandel stickers niet als bescherming en verbeter je verpakkingsmix op basis van schade en toeslagen.",
    faqs: [
      { question: "Waarom beïnvloedt de doosmaat de verzendkosten?", answer: "Vervoerders kunnen werken met formaatstaffels, afwijkend-formaattoeslagen of volumetrisch gewicht. Daardoor kan een grote lichte doos duurder zijn." },
      { question: "Helpt een breekbaar-sticker tegen schade?", answer: "De sticker vervangt geen goede verpakking en garandeert geen aparte behandeling. Bij sommige diensten kan hij tot handmatige verwerking en een toeslag leiden." },
      { question: "Moet ik het product of de doos meten?", answer: "Meet de volledig gesloten buitenzijde van de verzendverpakking, inclusief eventuele uitstekende delen." },
      { question: "Wanneer zijn dozen op maat interessant?", answer: "Vooral bij een voorspelbaar assortiment en voldoende volume, wanneer lagere materiaal-, vul- en verzendkosten de extra inkoop compenseren." },
    ],
    sources: [
      { label: "PostNL: pakket adresseren en verpakken", href: "https://www.postnl.nl/versturen/pakket-versturen/hoe-verstuur-ik-een-pakket/pakket-adresseren-en-verpakken/" },
      { label: "PostNL: toeslagen voor handmatige verwerking", href: "https://www.postnl.nl/zakelijk/klantenservice/facturen/alles-over-facturen-en-kosten/" },
      { label: "FedEx: voorbeeldberekening volumetrisch gewicht", href: "https://www.fedex.com/en-nl/shipping/international/international-connect.html" },
    ],
    about: ["Verpakking", "Volumetrisch gewicht", "Pakketschade", "Verzendkosten", "Webshop"], breadcrumb: "Juiste verpakking kiezen",
  },

  "/kennisbank/webshop-koppelen-verzendplatform": {
    title: "Webshop koppelen aan een verzendplatform: waarom en hoe werkt het?",
    seoTitle: "Webshop koppelen aan een verzendplatform | Sendwise",
    description: "Lees hoe een verzendplatform webshoporders omzet in labels en tracking, welke fouten automatisering voorkomt en wanneer koppelen interessant wordt.",
    excerpt: "Koppel orders, labels en tracking aan elkaar en voorkom handmatig overtypen zodra je webshop groeit.",
    type: "Handleiding", category: "Integraties", readTime: "± 6 min", publishedTime: "2026-08-18",
    image: "/sendwise-platform-dashboard-hero.webp", imageAlt: "Sendwise-dashboard waarin webshoporders en zendingen samenkomen", imageClassName: "object-contain p-3", imageBackground: "bg-[#edf4ff]",
    quickAnswer: "Een verzendplatform haalt orders uit je webshop, gebruikt de ordergegevens voor zendingen en labels en kan tracking terugkoppelen. Dat bespaart handwerk en maakt meerdere vervoerders vanuit één proces mogelijk. De businesscase hangt af van ordervolume, foutkosten, koppelmogelijkheden en tariefvoorwaarden.",
    introTitle: "De schakel tussen bestelling en vervoerder", introEyebrow: "Van order naar label",
    intro: ["Bij handmatig verzenden kopieer je adressen en kies je per order een dienst. Een koppeling laat dezelfde gegevens gecontroleerd doorstromen naar het verzendproces.", "Automatisering voorkomt niet elke fout: productdata, adres, gewicht en verpakkingskeuze moeten nog steeds juist zijn."],
    sections: [
      { id: "werking", eyebrow: "Eén gegevensstroom", title: "Zo werkt een verzendkoppeling", steps: ["De webshop stelt een nieuwe order beschikbaar aan de integratie.", "De order verschijnt met klant-, adres- en productgegevens in het verzendplatform.", "Een gebruiker of verzendregel kiest de passende dienst en maakt het label.", "Tracking en verzendstatus gaan waar ondersteund terug naar het verkoopkanaal."]},
      { id: "voordelen", eyebrow: "Minder losse handelingen", title: "De belangrijkste voordelen", items: [
        { title: "Tijdsbesparing", text: "Maak labels in batches of vanuit een vaste workflow in plaats van order voor order." },
        { title: "Minder invoerfouten", text: "Adres- en ordergegevens hoeven niet opnieuw te worden overgetypt." },
        { title: "Multi-carrier", text: "Gebruik meerdere vervoerders zonder per order tussen losse portals te wisselen." },
        { title: "Centrale tracking", text: "Houd zendingen en vervolgacties gekoppeld aan de oorspronkelijke order." },
      ]},
      { id: "businesscase", eyebrow: "Niet alleen pakketten tellen", title: "Wanneer is koppelen de moeite waard?", paragraphs: ["Kijk naast het aantal pakketten naar minuten per order, foutcorrecties, klantenservice, aantal verkoopkanalen en behoefte aan meerdere vervoerders.", "Ook bij een bescheiden volume kan koppelen lonen wanneer je complexe orders of meerdere kanalen hebt. Vergelijk tarieven altijd inclusief voorwaarden en toeslagen." ]},
    ],
    sendwise: "Sendwise koppelt met verschillende webshop- en WMS-systemen. Orders komen centraal binnen, labels worden vanuit dezelfde order gemaakt en tracking kan terug naar de gekoppelde omgeving. De beschikbare functies verschillen per integratie.",
    summary: "Een verzendplatform verbindt order, label, vervoerder en tracking. Dat vermindert handmatig werk en maakt groei beter beheersbaar, mits je stamgegevens en verzendregels goed inricht.",
    faqs: [
      { question: "Wat doet een verzendplatform?", answer: "Het brengt orders, vervoerdersdiensten, labels, tracking en vaak retouren samen in één verzendworkflow." },
      { question: "Voorkomt een koppeling alle verzendfouten?", answer: "Nee. Overtypen neemt af, maar onjuiste product-, adres-, gewicht- of verpakkingsgegevens kunnen nog steeds fouten veroorzaken." },
      { question: "Kan ik meerdere vervoerders koppelen?", answer: "Ja, een multi-carrierplatform kan meerdere vervoerders centraal beschikbaar maken, afhankelijk van je account en diensten." },
      { question: "Is koppelen alleen interessant bij hoog volume?", answer: "Niet per se. Meerdere kanalen, complexe orders en veel handmatig werk kunnen ook bij lager volume een duidelijke businesscase geven." },
    ],
    sources: [{ label: "Sendwise: overzicht van integraties", href: "https://www.sendwise.nl/integraties" }],
    about: ["Webshop koppelen", "Verzendplatform", "Integratie", "Verzendlabels", "Automatisering"], breadcrumb: "Webshop koppelen aan verzendplatform",
  },

  "/kennisbank/sendwise-webshopsoftware-integraties": {
    title: "Met welke webshopsoftware werkt Sendwise samen?",
    seoTitle: "Sendwise-integraties voor webshopsoftware en WMS",
    description: "Bekijk met welke webshopsoftware, marketplace en WMS-systemen Sendwise koppelt en wanneer een standaardintegratie of maatwerkkoppeling past.",
    excerpt: "Bekijk de actuele Sendwise-koppelingen voor webshops, bol.com en WMS-systemen en ontdek wat een integratie automatiseert.",
    type: "Blog", category: "Integraties", readTime: "± 6 min", publishedTime: "2026-08-18",
    image: "/sendwise-api.webp", imageAlt: "Sendwise API als basis voor een maatwerkintegratie", imageClassName: "object-contain p-12", imageBackground: "bg-[#fff7e7]",
    quickAnswer: "De huidige Sendwise-website vermeldt WooCommerce, Shopify, CCV Shop, Lightspeed, Magento, Mijnwebwinkel, Ecwid, Wix en PrestaShop als webshopkoppelingen, bol.com als marketplace en Lyra en GoedGepickt als WMS-koppelingen. Voor andere orderflows kan een API- of maatwerkkoppeling worden besproken.",
    introTitle: "Kies de koppeling die bij je orderbron past", introEyebrow: "Webshop, marketplace of WMS",
    intro: ["Een integratie voorkomt losse exports en maakt van je verkoopkanaal en verzendproces één gegevensstroom.", "Niet iedere koppeling ondersteunt exact dezelfde velden of retourstroom. Controleer daarom per systeem welke order-, status- en trackingfuncties beschikbaar zijn."],
    sections: [
      { id: "webshops", eyebrow: "Actueel overzicht", title: "Ondersteunde webshopplatformen", items: [
        { title: "WooCommerce en Shopify", text: "Veelgebruikte platformen voor zelfstandige webshops en groeiende ordervolumes." },
        { title: "CCV Shop en Lightspeed", text: "Koppelingen voor Nederlandse retail- en omnichannelomgevingen." },
        { title: "Magento en PrestaShop", text: "Flexibele platformen voor uitgebreidere catalogi en maatwerkflows." },
        { title: "Wix, Ecwid en Mijnwebwinkel", text: "Toegankelijke webshopoplossingen waarvan orders naar Sendwise kunnen doorstromen." },
      ]},
      { id: "marketplace-wms", eyebrow: "Meer dan webshops", title: "Marketplace en WMS", paragraphs: ["bol.com staat als marketplace-integratie in het actuele overzicht. Voor magazijn- en fulfilmentprocessen vermeldt Sendwise Lyra en GoedGepickt.", "Channeldock staat niet in het huidige publieke integratieoverzicht en is daarom niet als actieve standaardkoppeling opgenomen. Vraag Sendwise naar de actuele status wanneer dit systeem voor jou relevant is."]},
      { id: "maatwerk", eyebrow: "Voor afwijkende processen", title: "API en maatwerk", paragraphs: ["Sendwise biedt een API-route voor order- en verzendflows. De precieze endpoints, authenticatie en mogelijkheden horen bij de actuele technische documentatie.", "Breng vóór ontwikkeling ordervelden, retourstatussen, foutafhandeling, rate limits en terugkoppeling naar het bronsysteem in kaart."]},
    ],
    sendwise: "Op de integratiepagina zie je welke koppelingen momenteel publiek worden aangeboden. Staat je systeem er niet bij, dan kan Sendwise beoordelen of een bestaande koppeling, WMS-route of maatwerk via API passend is.",
    summary: "Sendwise koppelt met negen genoemde webshopplatformen, bol.com en de WMS-systemen Lyra en GoedGepickt. Controleer per integratie de ondersteunde gegevens en bespreek afwijkende systemen als maatwerk.",
    faqs: [
      { question: "Werkt Sendwise met Shopify en WooCommerce?", answer: "Ja, beide platformen staan in het actuele Sendwise-integratieoverzicht." },
      { question: "Kan ik bol.com-orders in Sendwise verwerken?", answer: "bol.com staat als marketplace-integratie vermeld. Controleer bij inrichting welke order- en trackingfuncties voor jouw account beschikbaar zijn." },
      { question: "Welke WMS-systemen worden genoemd?", answer: "De huidige website vermeldt Lyra en GoedGepickt." },
      { question: "Wat als mijn platform niet in het overzicht staat?", answer: "Bespreek dan een maatwerk- of API-koppeling en laat de benodigde gegevensstroom vooraf technisch beoordelen." },
    ],
    sources: [{ label: "Sendwise: actuele integraties", href: "https://www.sendwise.nl/integraties" }],
    about: ["Sendwise-integraties", "Shopify", "WooCommerce", "bol.com", "WMS"], breadcrumb: "Sendwise-integraties",
  },

  "/kennisbank/veelgestelde-vragen-pakketverzending": {
    title: "Veelgestelde vragen over pakketverzending voor webshops",
    seoTitle: "Veelgestelde vragen over pakketverzending | Sendwise",
    description: "Antwoorden op veelgestelde vragen over vervoerders, verzendkosten, verpakking, schade, retouren, webshopkoppelingen en internationale zendingen.",
    excerpt: "Praktische antwoorden op de belangrijkste vragen van webshops over vervoerders, kosten, problemen, retouren en integraties.",
    type: "Blog", category: "Verzendproces", readTime: "± 9 min", publishedTime: "2026-08-18",
    image: "/sendwise-hero-delivery-van.jpg", imageAlt: "Sendwise-bezorger laadt pakketten in een bezorgbus",
    quickAnswer: "Er is geen beste vervoerder of verzendstrategie voor iedere webshop. Pakketprofiel, bestemming, waarde, service en volume bepalen de juiste keuze. Vergelijk totale kosten, richt verpakking en retouren vooraf in en automatiseer terugkerend werk zodra dat tijd of fouten bespaart.",
    introTitle: "Snel antwoord op veelvoorkomende verzendvragen", introEyebrow: "Van vervoerder tot retour",
    intro: ["Deze verzamelpagina geeft korte antwoorden en verwijst naar verdiepende artikelen in de kennisbank.", "Voor actuele tarieven, limieten, dekking en claimtermijnen blijven de productvoorwaarden van de gekozen vervoerder leidend."],
    sections: [
      { id: "vervoerders-kosten", eyebrow: "Keuze en prijs", title: "Vervoerders en verzendkosten", items: [
        { title: "Is er één beste vervoerder?", text: "Nee. Product, formaat, waarde, bestemming, bezorgoptie en volume bepalen welke dienst past." },
        { title: "Kan ik meerdere vervoerders gebruiken?", text: "Ja. Dat biedt flexibiliteit, maar vraagt duidelijke regels om fouten en onnodige complexiteit te voorkomen." },
        { title: "Wat is volumetrisch gewicht?", text: "Een rekengewicht op basis van afmetingen. De formule en toepassing verschillen per vervoerder en dienst." },
        { title: "Is gratis verzending altijd beter?", text: "Nee. Beoordeel conversie samen met marge, orderwaarde, retouren en totale logistieke kosten." },
      ]},
      { id: "problemen-retouren", eyebrow: "Als iets anders loopt", title: "Schade, vermissing en retouren", items: [
        { title: "Wat als een pakket kwijt is?", text: "Controleer scans, meld tijdig bij je verzendpartner en bewaar order-, waarde- en verzendbewijs. Dekking verschilt per dienst." },
        { title: "Wanneer is een zwaar-label nodig?", text: "Alleen wanneer de gekozen vervoerder of dienst dit voorschrijft. Gewichtslimieten en toeslagen verschillen." },
        { title: "Verzendkosten terugbetalen?", text: "Bij volledige herroeping moet de standaardlevering doorgaans worden terugbetaald; deelretouren liggen genuanceerder." },
        { title: "Retouren uit het buitenland?", text: "Ja, maar tarief, beschikbaarheid en douanedocumentatie verschillen per route." },
      ]},
      { id: "techniek", eyebrow: "Automatiseren", title: "Techniek en integraties", paragraphs: ["Een webshopkoppeling is niet verplicht, maar vermindert overtypen en maakt labels en tracking schaalbaarder.", "Sendwise vermeldt verschillende webshop-, marketplace- en WMS-koppelingen. Controleer het actuele integratieoverzicht voor jouw systeem." ]},
    ],
    sendwise: "Sendwise helpt vervoerders, labels, tracking en retouren in één proces te organiseren. Voor een specifiek antwoord kijken we naar je eigen producten, bestemmingen en volume.",
    summary: "Gebruik de korte antwoorden als startpunt en controleer bij een definitieve keuze altijd actuele tarieven, productvoorwaarden en wettelijke regels.",
    faqs: [
      { question: "Is er één beste vervoerder voor elke webshop?", answer: "Nee. De passende vervoerder hangt af van product, formaat, waarde, bestemming, bezorgopties, volume en totale kosten." },
      { question: "Kan ik met meerdere vervoerders tegelijk werken?", answer: "Ja. Leg wel vaste verzendregels vast zodat de keuze consistent en controleerbaar blijft." },
      { question: "Wat is volumetrisch gewicht?", answer: "Een rekengewicht op basis van pakketafmetingen. De exacte formule en toepassing verschillen per vervoerder en dienst." },
      { question: "Is ieder pakket standaard verzekerd?", answer: "Nee. Dekking en aansprakelijkheid verschillen sterk per product. Controleer dit vóór verzending van waardevolle goederen." },
      { question: "Kan ik internationale retouren ontvangen?", answer: "Ja, voor veel landen. Tarief, dienstbeschikbaarheid en eventuele douanedocumenten verschillen per route." },
      { question: "Moet ik mijn webshop koppelen?", answer: "Het is niet verplicht, maar kan overtypen, fouten en handmatig statuswerk aanzienlijk verminderen." },
    ],
    sources: [
      { label: "PostNL: zakelijke pakketformaten en gewichten", href: "https://www.postnl.nl/zakelijk/klantenservice/servicekaders/pakket-grootte-gewicht/" },
      { label: "DHL eCommerce: zakelijke pakketformaten", href: "https://www.dhlecommerce.nl/nl/zakelijk/support/verzenden/afmetingen-en-gewicht" },
      { label: "Nederlandse wet: terugbetaling bij herroeping", href: "https://wetten.overheid.nl/BWBR0005289/2022-01-01/0/Boek6" },
    ],
    about: ["Pakketverzending", "Veelgestelde vragen", "Vervoerders", "Retouren", "Webshops"], breadcrumb: "Veelgestelde vragen pakketverzending",
  },

  "/kennisbank/track-trace-eigen-huisstijl": {
    title: "Track & trace in eigen huisstijl: waarom branded tracking je klantervaring verbetert",
    seoTitle: "Track & trace in eigen huisstijl voor webshops | Sendwise",
    description: "Ontdek hoe branded track & trace en herkenbare e-mails klanten meer bezorginzicht geven, WISMO-vragen kunnen beperken en je merk zichtbaar houden.",
    excerpt: "Houd klanten na checkout in je eigen merkervaring met herkenbare trackingpagina’s, e-mails en actuele bezorginformatie.",
    type: "Blog", category: "Klantervaring", readTime: "± 6 min", publishedTime: "2026-08-18",
    image: "/sendwise-platform-dashboard-hero.webp", imageAlt: "Sendwise-dashboard voor zendingen en tracking", imageClassName: "object-contain p-3", imageBackground: "bg-[#edf4ff]",
    quickAnswer: "Branded tracking toont verzendstatus en notificaties in een herkenbare omgeving met je eigen logo, kleuren en afzender. Duidelijke actuele informatie kan WISMO-vragen beperken en houdt de klantreis bij je webshop. Het effect hangt af van datakwaliteit, timing en begrijpelijke statusteksten.",
    introTitle: "De klantreis stopt niet bij de betaalbevestiging", introEyebrow: "Where is my order?",
    intro: ["Na checkout wil de klant vooral weten of de bestelling is verwerkt en wanneer deze aankomt. Realtime tracking wordt in actueel e-commerceonderzoek als belangrijke bezorgverwachting genoemd.", "Een eigen vormgeving helpt alleen wanneer de informatie klopt. Een mooie pagina met onduidelijke of verouderde status voorkomt geen klantvragen."],
    sections: [
      { id: "wat-is-het", eyebrow: "Herkenbare verzendcommunicatie", title: "Wat is branded track & trace?", paragraphs: ["De trackingpagina en e-mails sluiten visueel en tekstueel aan op je webshop, terwijl vervoerdersscans de logistieke status voeden.", "Maak duidelijk welke informatie van de vervoerder komt en bied een bereikbare route voor vragen of afwijkingen."]},
      { id: "voordelen", eyebrow: "Na aankoop", title: "Waarom dit waarde kan toevoegen", items: [
        { title: "Meer zelfservice", text: "Een duidelijke tijdlijn helpt klanten eerst zelf de actuele status te controleren." },
        { title: "Consistente merkbeleving", text: "Logo, tone of voice en kleuren blijven herkenbaar na checkout." },
        { title: "Gerichte service", text: "Toon hulp bij vertraging, fout adres of gemiste bezorging op het juiste moment." },
        { title: "Relevante vervolgstap", text: "Een servicebericht of passend product kan nuttig zijn, zolang tracking centraal blijft en marketing niet overheerst." },
      ]},
      { id: "inrichten", eyebrow: "Informatie vóór promotie", title: "Zo richt je tracking goed in", steps: ["Gebruik begrijpelijke statussen en een duidelijke verwachte bezorging.", "Stuur alleen notificaties die nieuwe, relevante informatie bevatten.", "Test afzender, links, mobiele leesbaarheid en fallback bij ontbrekende scans.", "Meet WISMO-contacten, klikgedrag en klanttevredenheid vóór en na invoering."]},
    ],
    sendwise: "Sendwise ondersteunt trackingpagina’s en trackingmails die aansluiten op je eigen merk. De beschikbare inrichting en statusgegevens hangen samen met je vervoerder en gekozen integratie.",
    summary: "Branded tracking combineert bezorginzicht met een herkenbare merkervaring. Zorg eerst dat status, timing en hulpacties duidelijk zijn en meet vervolgens het effect op WISMO en klanttevredenheid.",
    faqs: [
      { question: "Wat betekent WISMO?", answer: "WISMO staat voor ‘Where Is My Order’: vragen van klanten over de status en verwachte bezorging." },
      { question: "Wat is branded tracking?", answer: "Een trackingervaring met je eigen logo, kleuren, tone of voice en service-informatie, gevoed door vervoerdersstatussen." },
      { question: "Vermindert branded tracking altijd klantvragen?", answer: "Niet automatisch. De informatie moet actueel, begrijpelijk en bereikbaar zijn. Meet het effect op je eigen klantenservice." },
      { question: "Kan Sendwise trackingmails in huisstijl versturen?", answer: "De Sendwise-website vermeldt eigen trackingmails en herkenbare trackingpagina’s als platformmogelijkheid." },
    ],
    sources: [
      { label: "Sendwise: platform en verzendcommunicatie", href: "https://www.sendwise.nl/oplossingen/sendwise" },
      { label: "DHL: E-Commerce Trends Report 2025", href: "https://www.dhl.com/global-en/microsites/ec/ecommerce-insights/insights/reports/2025-ecommerce-trends-report.html" },
    ],
    about: ["Track en trace", "Branded tracking", "WISMO", "Klantervaring", "Verzendcommunicatie"], breadcrumb: "Track & trace in eigen huisstijl",
  },

  "/kennisbank/beschadigd-verloren-gestolen-pakket": {
    title: "Beschadigd, verloren of gestolen pakket: wat nu?",
    seoTitle: "Beschadigd of vermist pakket: stappen en claim | Sendwise",
    description: "Wat doe je bij een beschadigd, verloren of mogelijk gestolen pakket? Volg het stappenplan voor bewijs, melding, klantcommunicatie en een eventuele claim.",
    excerpt: "Meld problemen snel, bewaar doos, label en bewijsstukken en controleer de dekking van de gekozen vervoerdersdienst.",
    type: "Handleiding", category: "Klantenservice", readTime: "± 7 min", publishedTime: "2026-08-18",
    image: "/kennisbank-beschadigd-pakket.jpg", imageAlt: "Zwaar beschadigde kartonnen verzenddoos",
    quickAnswer: "Controleer eerst tracking en bezorgbewijs, meld het probleem binnen de termijn van de vervoerder en bewaar doos, label, inhoud, foto’s en waardebewijs. Informeer de klant proactief, maar beloof geen vergoeding voordat aansprakelijkheid en verzekering zijn vastgesteld. Niet iedere standaardzending is verzekerd.",
    introTitle: "Snel handelen zonder te vroeg conclusies te trekken", introEyebrow: "Schade, verlies of diefstal",
    intro: ["Een zending kan beschadigd zijn, geen nieuwe scan krijgen of als bezorgd staan terwijl de ontvanger niets heeft. Die situaties vragen elk om een eigen onderzoek.", "De oorspronkelijke verkoper blijft richting de consument verantwoordelijk voor correcte levering; de vervoerdersclaim is een afzonderlijk traject tussen verzendende partij en vervoerder."],
    sections: [
      { id: "stappen", eyebrow: "Dossier opbouwen", title: "Wat je direct moet doen", steps: ["Controleer tracking, adres, bezorgbewijs en eventuele aflevervoorkeur.", "Vraag de ontvanger om verpakking, label en inhoud te bewaren en duidelijke foto’s te maken.", "Meld de zending binnen de productgebonden termijn bij je verzendpartner.", "Leg contactmomenten, orderwaarde, inkoopbewijs en gewenste oplossing vast."]},
      { id: "dekking", eyebrow: "Controleer het verzendproduct", title: "Aansprakelijkheid is niet hetzelfde als verzekering", paragraphs: ["PostNL vermeldt dat onverzekerde pakketten bij beschadiging niet voor schadevergoeding in aanmerking komen. DHL wijst erop dat zonder aanvullende verzekering alleen wettelijke aansprakelijkheid geldt, vaak op basis van gewicht.", "Controleer vóór waardevolle zendingen dekking, uitsluitingen, maximale vergoeding, verpakkingseisen en claimtermijnen. Ondeugdelijke verpakking kan een claim uitsluiten."]},
      { id: "klant", eyebrow: "Behoud vertrouwen", title: "Communiceer proactief met de klant", items: [
        { title: "Erken het probleem", text: "Bevestig wat je weet, wat nog onderzocht wordt en wanneer de volgende update volgt." },
        { title: "Bied een passende oplossing", text: "Maak je consumentenverplichting niet afhankelijk van hoe snel de vervoerder jouw claim afhandelt." },
        { title: "Geen voorbarige conclusie", text: "Een bezorgdscan bewijst niet automatisch diefstal; controleer afleverlocatie en bewijs." },
        { title: "Leer van patronen", text: "Meet schade en vermissing per verpakking, dienst, regio en productwaarde." },
      ]},
    ],
    sendwise: "Bij Sendwise kun je een probleem met een zending melden en ondersteunen we het onderzoek bij de vervoerder. Doorlooptijd en eventuele vergoeding blijven afhankelijk van vervoerder, verzendproduct, bewijs en voorwaarden.",
    summary: "Bouw snel een volledig dossier op, communiceer met de klant en controleer de specifieke dekking. Ga niet uit van een standaardverzekering en scheid de klantoplossing van de vervoerdersclaim.",
    faqs: [
      { question: "Welke foto’s zijn nodig bij transportschade?", answer: "Maak foto’s van buitenverpakking, binnenverpakking, label, schade aan de inhoud en een overzicht van de complete zending." },
      { question: "Is een standaardpakket verzekerd?", answer: "Niet automatisch. Dekking, aansprakelijkheid en vergoeding verschillen per vervoerder en product." },
      { question: "Hoe snel moet ik schade melden?", answer: "Binnen de termijn van de gekozen dienst. PostNL noemt voor bepaalde zakelijke schademeldingen zeven dagen; controleer altijd je eigen voorwaarden." },
      { question: "Mag ik wachten op de vervoerdersclaim voordat ik de klant help?", answer: "Bij consumentenkoop ligt het leveringsrisico doorgaans bij de verkoper tot ontvangst. Behandel de klantoplossing daarom niet automatisch als afhankelijk van de claim." },
    ],
    sources: [
      { label: "PostNL: beschadigd pakket melden", href: "https://www.postnl.nl/zakelijk/klantenservice/versturen-bezorgen/probleem-pakket-post/beschadigd/" },
      { label: "DHL eCommerce: zakelijk verzekerd verzenden", href: "https://www.dhlecommerce.nl/nl/zakelijk/verzekerd-verzenden" },
    ],
    about: ["Beschadigd pakket", "Vermist pakket", "Claim", "Verzekering", "Klantenservice"], breadcrumb: "Beschadigd of vermist pakket",
  },

  "/kennisbank/verzendkosten-berekenen": {
    title: "Verzendkosten berekenen: complete uitleg voor webshops",
    seoTitle: "Verzendkosten berekenen voor je webshop | Sendwise",
    description: "Bereken de werkelijke verzendkosten per order met tarief, formaat, bestemming, toeslagen, pickup, verpakking, retouren en extra services.",
    excerpt: "Kijk verder dan het labeltarief en bereken per verzendprofiel de volledige kosten van verpakking tot retour.",
    type: "Handleiding", category: "Verzendkosten", readTime: "± 8 min", publishedTime: "2026-08-18",
    image: "/kennisbank-drempelbedrag.jpg", imageAlt: "Veel pakketten als illustratie van totale verzendkosten",
    quickAnswer: "Werkelijke verzendkosten bestaan uit het vervoerderstarief plus formaat- en gewichtscorrecties, bestemming, gekozen service, brandstof- of piektoeslagen, pickup, verpakking, software, mislukte bezorgingen en retouren. Bereken gemiddelden per verzendprofiel in plaats van één bedrag voor alle orders.",
    introTitle: "Het labeltarief is slechts één onderdeel", introEyebrow: "Van basistarief tot retour",
    intro: ["Vervoerders hanteren verschillende producten, staffels en correcties. Een scherpe prijs op een standaardpakket zegt weinig wanneer veel van je orders buiten dat profiel vallen.", "Maak daarom groepen op basis van formaat, gewicht, bestemming en service en bereken per groep het volledige kostenniveau."],
    sections: [
      { id: "opbouw", eyebrow: "Directe transportkosten", title: "Welke factoren bepalen het tarief?", items: [
        { title: "Gewicht en formaat", text: "Werkelijk gewicht, volume, langste zijde en afwijkende vorm kunnen een andere categorie of toeslag geven." },
        { title: "Bestemming", text: "Land, regio, eiland- of afgelegengebied en douane beïnvloeden prijs en doorlooptijd." },
        { title: "Afleverwijze", text: "Thuis, pakketpunt, brievenbus, zakelijk adres of tijdvak hebben eigen tarieven en voorwaarden." },
        { title: "Extra services", text: "Denk aan verzekering, handtekening, leeftijdscheck, aangetekend of express." },
      ]},
      { id: "totale-kosten", eyebrow: "Kosten buiten het label", title: "Neem de hele operatie mee", paragraphs: ["Tel verpakking, vulmateriaal, pick-en-packtijd, pickup, software, betaalfees, klantenservice en retouren mee.", "Controleer facturen op formaatcorrecties en toeslagen. ‘All-in’ kan betekenen dat bepaalde vaste componenten inbegrepen zijn, maar zendingsafhankelijke correcties blijven mogelijk." ]},
      { id: "rekenmodel", eyebrow: "Per profiel rekenen", title: "Bouw een bruikbaar kostenmodel", steps: ["Exporteer een representatieve periode met zending, maat, gewicht, bestemming en dienst.", "Koppel vervoerdersfacturen en correcties aan de oorspronkelijke orders.", "Bereken gemiddelde en spreiding per verzendprofiel, inclusief retouren.", "Gebruik de uitkomst voor checkouttarieven, gratis-verzenddrempels en vervoerdersregels."]},
    ],
    sendwise: "Sendwise werkt volgens de website zonder abonnementskosten en losse labelbijdrages en toont tarieven en zendingsafhankelijke toeslagen in het platform. Controleer altijd de actuele prijsafspraken voor jouw account en profiel.",
    summary: "Bereken kosten per werkelijk verzendprofiel en neem alle operationele componenten mee. Controleer toeslagen op factuurniveau en gebruik de uitkomst voor een realistische checkout- en vervoerdersstrategie.",
    faqs: [
      { question: "Waaruit bestaan verzendkosten?", answer: "Uit transporttarief, formaat en gewicht, bestemming, service, toeslagen, pickup, verpakking, verwerking, retouren en eventuele softwarekosten." },
      { question: "Wat is volumetrisch gewicht?", answer: "Een rekengewicht op basis van buitenafmetingen. De deler en toepassing verschillen per vervoerder en dienst." },
      { question: "Is pakketpuntbezorging altijd goedkoper?", answer: "Niet altijd. Dit verschilt per vervoerder, dienst, contract en bestemming." },
      { question: "Wat betekent all-in tarief?", answer: "Welke componenten inbegrepen zijn moet expliciet in de prijsvoorwaarden staan. Afwijkend formaat of bijzondere diensten kunnen alsnog apart worden berekend." },
    ],
    sources: [
      { label: "PostNL: zakelijke kosten en toeslagen", href: "https://www.postnl.nl/zakelijk/klantenservice/facturen/alles-over-facturen-en-kosten/" },
      { label: "DHL eCommerce: afmetingen en gewichten", href: "https://www.dhlecommerce.nl/nl/zakelijk/support/verzenden/afmetingen-en-gewicht" },
      { label: "Sendwise: verzendtarieven", href: "https://www.sendwise.nl/prijzen" },
    ],
    about: ["Verzendkosten berekenen", "Toeslagen", "Volumetrisch gewicht", "Tarieven", "Webshop"], breadcrumb: "Verzendkosten berekenen",
  },

  "/kennisbank/brievenbuspakket-of-pakket": {
    title: "Brievenbuspakket of pakket: wat is het verschil en wanneer kies je wat?",
    seoTitle: "Brievenbuspakket of pakket kiezen | Sendwise",
    description: "Vergelijk brievenbuspakket en standaardpakket op afmetingen, gewicht, tracking, bezorging, verzekering en prijs. Inclusief actuele limieten per vervoerder.",
    excerpt: "Een paar centimeter of een ander gewicht kan de verzendcategorie veranderen. Controleer daarom de limiet van de gekozen vervoerder en dienst.",
    type: "Blog", category: "Verpakking", readTime: "± 7 min", publishedTime: "2026-08-18",
    image: "/verzenden-afbeelding-1.png", imageAlt: "Keuze tussen brievenbuspakje en standaardpakket in Sendwise", imageClassName: "object-contain p-6", imageBackground: "bg-[#edf4ff]",
    quickAnswer: "Een brievenbuspakket past door de standaardbrievenbus en hoeft meestal niet persoonlijk te worden aangenomen. De bekende maximale maat is vaak 38 × 26,5 × 3,2 cm, maar het maximale gewicht en de voorwaarden verschillen: PostNL noemt zakelijk tot 2 kg, DHL eCommerce zakelijk momenteel tot 1 kg. Controleer dus altijd de gekozen dienst.",
    introTitle: "De categorie wordt bepaald door productvoorwaarden", introEyebrow: "Klein verschil, andere dienst",
    intro: ["Brievenbuszendingen zijn efficiënt omdat de ontvanger niet thuis hoeft te zijn. Ze kunnen voordeliger zijn, maar tracking, aansprakelijkheid en maximale inhoud verschillen per product.", "De stelling dat PostNL, DHL en DPD altijd dezelfde limiet hanteren is niet veilig. Zelfs zakelijke en consumentenproducten van dezelfde vervoerder kunnen verschillen."],
    sections: [
      { id: "brievenbus", eyebrow: "Klein en plat", title: "Wat is een brievenbuspakket?", paragraphs: ["De buitenverpakking moet volledig binnen de limieten vallen en voldoende stevig zijn voor automatische verwerking.", "PostNL vermeldt voor het zakelijke brievenbuspakje maximaal 38 × 26 × 3,2 cm en 2 kg. DHL eCommerce vermeldt zakelijk maximaal 38 × 26,5 × 3,2 cm en 1 kg; controleer de actuele contractvoorwaarden." ]},
      { id: "standaard", eyebrow: "Voor grotere zendingen", title: "Wanneer kies je een standaardpakket?", items: [
        { title: "Te groot of zwaar", text: "Zodra één limiet van het brievenbusproduct wordt overschreden, kies je een passende pakketdienst." },
        { title: "Meer bescherming nodig", text: "Kwetsbare producten kunnen een dikkere doos en extra interne bescherming vragen." },
        { title: "Hogere waarde", text: "Kies op basis van tracking, handtekening en verzekering, niet alleen op formaat." },
        { title: "Specifieke bezorgoptie", text: "Pakketpunt, tijdvak of aanvullende service kan een standaardpakketproduct vereisen." },
      ]},
      { id: "optimaliseren", eyebrow: "Meet verzendklaar", title: "Zo voorkom je een onnodig duur pakket", steps: ["Meet het product inclusief beschermende verpakking.", "Test of de gesloten zending zonder kracht door een brievenbusmal past.", "Controleer gewicht en limiet van de specifieke vervoerdersdienst.", "Vergelijk tarief, tracking, aansprakelijkheid en klantbelofte als totaal."]},
    ],
    sendwise: "In Sendwise kies je uit beschikbare brievenbus- en pakketdiensten. We helpen je productprofielen aan een passende categorie te koppelen, maar de actuele vervoerdersvoorwaarden blijven leidend.",
    summary: "Gebruik niet één universele limiet voor alle vervoerders. Meet de verzendklare verpakking en vergelijk naast prijs ook gewichtslimiet, tracking, dekking en bezorgbelofte.",
    faqs: [
      { question: "Hoe groot mag een brievenbuspakket zijn?", answer: "Veel diensten gebruiken ongeveer 38 × 26,5 × 3,2 cm, maar controleer de exacte maat van jouw vervoerder en contract." },
      { question: "Hoe zwaar mag een brievenbuspakket zijn?", answer: "Dat verschilt. PostNL noemt zakelijk tot 2 kg, DHL eCommerce zakelijk momenteel tot 1 kg." },
      { question: "Is een brievenbuspakket verzekerd?", answer: "Niet automatisch. PostNL vermeldt bijvoorbeeld dat het consumentenbrievenbuspakje niet verzekerd is." },
      { question: "Moet de klant thuis zijn?", answer: "Normaal niet wanneer de zending werkelijk door de brievenbus past, maar de exacte bezorgwijze volgt uit het gekozen product." },
    ],
    sources: [
      { label: "PostNL: zakelijke pakketformaten", href: "https://www.postnl.nl/zakelijk/klantenservice/servicekaders/pakket-grootte-gewicht/" },
      { label: "DHL eCommerce: zakelijke afmetingen en gewichten", href: "https://www.dhlecommerce.nl/nl/zakelijk/support/verzenden/afmetingen-en-gewicht" },
      { label: "PostNL: eigenschappen van het brievenbuspakje", href: "https://www.postnl.nl/klantenservice/verzendopties/brievenbuspakje/" },
    ],
    about: ["Brievenbuspakket", "Pakketformaat", "Verpakking", "PostNL", "DHL"], breadcrumb: "Brievenbuspakket of pakket",
  },

  "/kennisbank/labelprinter-kiezen": {
    title: "Labelprinter kiezen voor je webshop: welke past bij jouw volume?",
    seoTitle: "Labelprinter kiezen voor verzendlabels | Sendwise",
    description: "Kies een labelprinter voor je webshop op printtechniek, labelbreedte, resolutie, snelheid, aansluiting, compatibiliteit en dagelijks volume.",
    excerpt: "Direct thermisch is vaak praktisch voor verzendlabels; kies model, aansluiting en capaciteit op basis van je echte werkplek en volume.",
    type: "Handleiding", category: "Techniek", readTime: "± 7 min", publishedTime: "2026-08-18",
    image: "/kennisbank-labelprinter.jpg", imageAlt: "Thermische labelprinter die een verzendlabel print",
    quickAnswer: "Voor kortlevende verzendlabels is een direct thermische 4-inchprinter vaak passend: geen inkt, toner of lint en een scherpe barcode. Kies niet alleen op printsnelheid, maar ook op labelbreedte, resolutie, besturingssysteem, USB of netwerk, driverondersteuning en de printmethode van je verzendsoftware.",
    introTitle: "Kies de printer voor je workflow, niet alleen je volume", introEyebrow: "Van enkele labels tot een paktafel",
    intro: ["Een gewone printer kan bij laag volume voldoen, maar vraagt snijden of losse labelvellen. Een labelprinter print direct op zelfklevend materiaal.", "Compatibiliteit is essentieel: controleer formaat, drivers, browser- of printapp en het besturingssysteem vóór aanschaf."],
    sections: [
      { id: "techniek", eyebrow: "Twee printmethoden", title: "Direct thermisch of thermisch transfer?", items: [
        { title: "Direct thermisch", text: "Gebruikt hittegevoelig labelmateriaal en geen lint. Geschikt voor kortlevende toepassingen zoals verzendlabels." },
        { title: "Thermisch transfer", text: "Gebruikt een lint en is duurzamer bij licht, wrijving, chemicaliën of langdurige opslag." },
      ]},
      { id: "criteria", eyebrow: "Aanschafchecklist", title: "Waar je verder op let", items: [
        { title: "Breedte en resolutie", text: "Veel verzendlabels vragen circa 4 inch breedte; kleine barcodes kunnen hogere resolutie vereisen." },
        { title: "Aansluiting", text: "USB is eenvoudig voor één werkplek; LAN of wifi kan nuttig zijn voor meerdere gebruikers." },
        { title: "Werkbelasting", text: "Controleer aanbevolen dagelijks volume, printsnelheid, rolcapaciteit en vervangbare slijtdelen." },
        { title: "Software", text: "Bevestig drivers, printertaal, besturingssysteem en ondersteuning door je verzendplatform." },
      ]},
      { id: "testen", eyebrow: "Voor je bestelt", title: "Test de volledige printketen", steps: ["Download een echt label uit je verzendsoftware.", "Controleer formaat, oriëntatie, schaal en barcodekwaliteit.", "Test USB of netwerk vanaf iedere gebruikte werkplek.", "Bereken kosten van printer, labels, lint indien nodig en onderhoud per jaar."]},
    ],
    sendwise: "Sendwise genereert labels voor de gekozen vervoerdersdienst. Controleer vóór aanschaf welke printmethode en printerinstellingen jouw werkplek gebruikt; Sendwise kan meedenken over een passende configuratie.",
    summary: "Direct thermisch past vaak goed bij verzendlabels, maar kies het concrete model op breedte, resolutie, aansluiting, werkbelasting en softwarecompatibiliteit. Test een echt label vóór aankoop.",
    faqs: [
      { question: "Heeft een direct thermische printer inkt nodig?", answer: "Nee. De printkop activeert hittegevoelig labelmateriaal; er is geen inkt, toner of lint nodig." },
      { question: "Wanneer kies je thermisch transfer?", answer: "Wanneer labels lang leesbaar moeten blijven of bestand moeten zijn tegen licht, warmte, vocht, chemicaliën of wrijving." },
      { question: "Is USB of netwerk beter?", answer: "USB is eenvoudig voor één computer. Een netwerkmodel is vaak praktischer wanneer meerdere werkplekken dezelfde printer gebruiken." },
      { question: "Welke labelbreedte heb ik nodig?", answer: "Veel pakketlabels gebruiken ongeveer 100 × 150 mm. Controleer altijd de formaten van je vervoerders en platform." },
    ],
    sources: [
      { label: "Zebra: direct thermisch versus thermisch transfer", href: "https://prod-www.zebra.com/us/en/resource-library/faq/difference-between-direct-thermal-and-thermal-transfer-printing.html" },
      { label: "Brother: professionele labelprinters voor logistiek", href: "https://www.brother.eu/-/media/pdf/nordics/transport-logistics-material/eng/warehouse-labelling-brochure.pdf" },
    ],
    about: ["Labelprinter", "Direct thermisch", "Verzendlabels", "Hardware", "Webshop"], breadcrumb: "Labelprinter kiezen",
  },

  "/kennisbank/verzendregels-automatiseren": {
    title: "Verzendregels automatiseren: automatisch de juiste vervoerder per bestelling kiezen",
    seoTitle: "Verzendregels automatiseren voor webshops | Sendwise",
    description: "Automatiseer vervoerder en verzendmethode op land, kanaal, gewicht, formaat en orderkenmerken. Inclusief prioriteit, uitzonderingen en testaanpak.",
    excerpt: "Laat terugkerende verzendkeuzes consistent uitvoeren met regels en houd uitzonderingen controleerbaar.",
    type: "Handleiding", category: "Techniek", readTime: "± 7 min", publishedTime: "2026-08-18",
    image: "/verzenden-afbeelding-1.png", imageAlt: "Automatische keuze uit verzendmethoden in Sendwise", imageClassName: "object-contain p-6", imageBackground: "bg-[#edf4ff]",
    quickAnswer: "Verzendregels kiezen op basis van ordergegevens automatisch een dienst. Begin met betrouwbare velden zoals land, verkoopkanaal, gewicht en verzendkeuze uit checkout. Leg prioriteit, fallback en uitzonderingen vast en test met historische orders voordat je labels automatisch laat aanmaken.",
    introTitle: "Maak terugkerende keuzes voorspelbaar", introEyebrow: "Automatisering met controle",
    intro: ["Zonder regels kiest een medewerker per order. Dat geeft flexibiliteit, maar ook variatie en fouten bij groei.", "Een regel is alleen zo betrouwbaar als de orderdata. Ontbrekende afmetingen of verkeerde gewichten kunnen automatisch de verkeerde dienst selecteren."],
    sections: [
      { id: "criteria", eyebrow: "Voorwaarden combineren", title: "Waarop kun je verzendregels baseren?", items: [
        { title: "Bestemming", text: "Land, postcodegebied of type adres kan een dienst of vervoerder bepalen." },
        { title: "Kanaal", text: "Gebruik per webshop, marketplace of integratie een eigen standaard of serviceniveau." },
        { title: "Pakketprofiel", text: "Gewicht, afmetingen, verpakking en productkenmerken bepalen welke dienst technisch past." },
        { title: "Orderbelofte", text: "Checkoutkeuze, cut-off en spoed kunnen de gewenste snelheid of afleverwijze bepalen." },
      ]},
      { id: "ontwerp", eyebrow: "Voorkom conflicten", title: "Denk aan prioriteit en fallback", paragraphs: ["Leg vast welke regel wint wanneer meerdere voorwaarden tegelijk gelden. Begin met uitsluitingen en specifieke regels en eindig met een veilige standaarddienst.", "Stuur onvolledige of uitzonderlijke orders naar handmatige controle in plaats van blind een label te maken." ]},
      { id: "testen", eyebrow: "Eerst simuleren", title: "Zo implementeer je regels veilig", steps: ["Analyseer welke keuzes medewerkers nu herhaaldelijk maken.", "Schrijf per regel invoer, uitkomst, prioriteit en fallback op.", "Test de regels met historische orders en bekende randgevallen.", "Monitor kosten, correcties en handmatige overrides na activering."]},
    ],
    sendwise: "De Sendwise-website vermeldt automatische verzendregels per order en keuze op basis van onder meer verzendmethode en klantgegevens. De beschikbare velden en verfijning hangen af van de platforminrichting.",
    summary: "Automatiseer alleen op betrouwbare data, geef specifieke regels prioriteit en houd een veilige fallback. Test historische orders en meet afwijkingen nadat de regels live staan.",
    faqs: [
      { question: "Wat is een verzendregel?", answer: "Een vooraf ingestelde voorwaarde die op basis van ordergegevens een vervoerder, dienst of vervolgactie kiest." },
      { question: "Kun je op land automatiseren?", answer: "Ja, bestemming is een veelgebruikt criterium, bijvoorbeeld met een standaarddienst per land." },
      { question: "Wat als orderdata ontbreekt?", answer: "Gebruik een fallback of handmatige controle. Laat ontbrekende maat- of gewichtsdata niet stilzwijgend een ongeschikte dienst kiezen." },
      { question: "Hoe test je verzendregels?", answer: "Draai historische orders en randgevallen door de regels en vergelijk de uitkomst met de gewenste keuze." },
    ],
    sources: [{ label: "Sendwise: verzendplatform", href: "https://www.sendwise.nl/oplossingen/sendwise" }],
    about: ["Verzendregels", "Automatisering", "Vervoerder kiezen", "Orderverwerking", "Webshop"], breadcrumb: "Verzendregels automatiseren",
  },

  "/kennisbank/verzenden-via-bol-com": {
    title: "Verzenden via bol.com: wat moet je weten als verkoper?",
    seoTitle: "Verzenden via bol.com als verkoper | Sendwise",
    description: "Vergelijk Verzenden via bol, Pakketzegels via bol, eigen verzendwijze en Logistiek via bol. Lees wat tracking en servicenormen betekenen.",
    excerpt: "Kies tussen logistieke diensten van bol en een eigen verzendwijze op basis van controle, servicenormen, pakketprofiel en totale kosten.",
    type: "Blog", category: "Marktplaatsen", readTime: "± 7 min", publishedTime: "2026-08-18",
    image: "/bol-logo.png", imageAlt: "bol-logo bij uitleg over verzendopties voor verkopers", imageClassName: "object-contain p-16", imageBackground: "bg-[#eef4ff]",
    quickAnswer: "bol noemt momenteel drie routes voor klantbestellingen: Verzenden via bol, Pakketzegels via bol en een eigen verzendwijze. Logistiek via bol is een fulfilmentdienst waarbij voorraad en klantbestellingen via bol worden verwerkt. Vergelijk kosten, pakketvoorwaarden, operationele controle en invloed op de servicenormen.",
    introTitle: "De verzendkeuze beïnvloedt je kwaliteitsscore", introEyebrow: "Verkopen via bol",
    intro: ["bol meet onder meer artikelen op tijd en Track & Trace. Een correcte en tijdige verzendbevestiging is daarom onderdeel van je marketplaceprestaties.", "De actuele opties en namen wijken af van een simpele driedeling tussen VvB, eigen verzending en LvB; controleer het Partnerplatform bij iedere proceswijziging."],
    sections: [
      { id: "opties", eyebrow: "Actuele routes", title: "Welke verzendopties noemt bol?", items: [
        { title: "Verzenden via bol", text: "Je koopt en gebruikt de aangeboden verzendroute en levert het pakket volgens de instructies aan." },
        { title: "Pakketzegels via bol", text: "Voordelige zegels voor genoemde vervoerders, met de bijbehorende aanlevervoorwaarden." },
        { title: "Eigen verzendwijze", text: "Je koopt verzending elders en bevestigt de bestelling met de correcte verzend- en trackinggegevens." },
        { title: "Logistiek via bol", text: "Voorraad ligt bij bol en bol verwerkt de fulfilment- en klantbestellingen volgens de LvB-voorwaarden." },
      ]},
      { id: "servicenormen", eyebrow: "Kwaliteit bewaken", title: "Let op Track & Trace en op-tijdprestaties", paragraphs: ["bol noemt Track & Trace en artikelen op tijd als onderdelen van de kwaliteitsscore. Te laat bevestigen of een onbruikbare code kan daarom gevolgen hebben.", "Controleer cut-off, vervoerdersscan en statuskoppeling dagelijks, vooral tijdens piekdrukte of bij een overstap van dienst." ]},
      { id: "kiezen", eyebrow: "Kosten en controle", title: "Vergelijk per pakketprofiel", steps: ["Breng formaat, gewicht, waarde en beloofde levertijd van bol-orders in kaart.", "Vergelijk zegelprijs met toeslagen, verwerking, retouren en foutkosten.", "Beoordeel hoeveel controle je wilt over vervoerder en fulfilment.", "Test de trackingterugkoppeling voordat je alle orders omzet."]},
    ],
    sendwise: "bol.com staat in het actuele Sendwise-integratieoverzicht. Daarmee kunnen marketplace-orders naast webshoporders in het verzendproces worden verwerkt. Laat bij inrichting bevestigen welke order- en trackingterugkoppeling voor jouw bol-configuratie wordt ondersteund.",
    summary: "bol biedt meerdere verzendroutes en een aparte fulfilmentdienst. Kies op totale kosten en controle en bewaak vooral tijdige verwerking en correcte tracking voor je kwaliteitsscore.",
    faqs: [
      { question: "Welke verzendopties biedt bol voor bestellingen?", answer: "Het Partnerplatform noemt Verzenden via bol, Pakketzegels via bol en een eigen verzendwijze. Logistiek via bol is de fulfilmentroute." },
      { question: "Is Track & Trace belangrijk voor bol?", answer: "Ja. Track & Trace en artikelen op tijd zijn onderdelen van de kwaliteitsscore." },
      { question: "Kan ik mijn eigen vervoerder gebruiken?", answer: "Ja, via een eigen verzendwijze, mits je de bestelling en tracking correct volgens de bol-voorwaarden verwerkt." },
      { question: "Kan Sendwise bol-orders verwerken?", answer: "bol.com staat als marketplace in het publieke Sendwise-integratieoverzicht. Controleer de precieze gegevensuitwisseling bij inrichting." },
    ],
    sources: [
      { label: "bol Partnerplatform: verzendopties", href: "https://partnerplatform.bol.com/nl/idp/verzendopties" },
      { label: "bol Partnerplatform: kwaliteitsscore", href: "https://partnerplatform.bol.com/nl/nadp/van-prestatiescore-naar-kwaliteitsscore" },
      { label: "bol Partnerplatform: Logistiek via bol", href: "https://partnerplatform.bol.com/nl/idp/bestelling-behandelen-via-lvb" },
    ],
    about: ["bol.com", "Verzenden via bol", "Logistiek via bol", "Marketplace", "Track en trace"], breadcrumb: "Verzenden via bol.com",
  },

  "/kennisbank/verzenden-startende-webshop": {
    title: "Verzenden als startende webshop of eenmanszaak: waar moet je op letten?",
    seoTitle: "Verzenden als startende webshop of eenmanszaak | Sendwise",
    description: "Starten met pakketten verzenden? Kies verpakking, vervoerder, verzendkosten, labels, tracking en retouren zonder direct een complex contract aan te gaan.",
    excerpt: "Begin professioneel en eenvoudig: kies een schaalbare verzendroute, communiceer duidelijk en houd kosten en retouren vanaf de eerste order bij.",
    type: "Blog", category: "Starters", readTime: "± 7 min", publishedTime: "2026-08-18",
    image: "/kennisbank-gratis-verzending.jpg", imageAlt: "Kleine webshop overhandigt een eerste pakket aan een bezorger",
    quickAnswer: "Een starter heeft vooral behoefte aan lage vaste lasten, duidelijke tarieven en een proces dat kan meegroeien. Vergelijk rechtstreeks boeken met een verzendplatform, maar neem geen tariefvoordeel als vanzelfsprekend aan. Richt vanaf de eerste order verpakking, tracking, verzendkosten en retourvoorwaarden professioneel in.",
    introTitle: "Begin eenvoudig, maar voorkom tijdelijk lapwerk", introEyebrow: "Van eerste order naar groei",
    intro: ["Bij laag volume is zelf aanleveren vaak praktischer dan een vaste pickup. Tegelijk wil je ordergegevens niet eindeloos handmatig blijven overtypen.", "Een platform kan toegang geven tot diensten zonder eigen vervoerderscontract, maar vergelijk altijd de actuele totaalprijs en voorwaarden voor jouw pakket."],
    sections: [
      { id: "basis", eyebrow: "Eerste keuzes", title: "Wat je vóór de eerste bestelling regelt", items: [
        { title: "Pakketprofiel", text: "Ken formaat, gewicht, kwetsbaarheid en waarde van je belangrijkste producten." },
        { title: "Verzendkosten", text: "Kies doorberekenen, gratis of een drempel op basis van marge en orderwaarde." },
        { title: "Aanlevering", text: "Vergelijk servicepunt, incidentele of vaste pickup op tijd en totale kosten." },
        { title: "Retourbeleid", text: "Publiceer termijn, kosten, uitzonderingen en werkwijze vóór je eerste verkoop." },
      ]},
      { id: "platform", eyebrow: "Contract of platform", title: "Vergelijk flexibiliteit en totaalprijs", paragraphs: ["Rechtstreeks boeken kan eenvoudig zijn, maar volumeafspraken en pickups verschillen. Een platform bundelt meerdere vervoerders en processen, maar is niet automatisch voor iedere zending goedkoper.", "Kijk naar labeltarief, toeslagen, vaste kosten, ondersteuning, integraties en hoe gemakkelijk je later een tweede vervoerder toevoegt." ]},
      { id: "groeien", eyebrow: "Meet vanaf dag één", title: "Bouw een proces dat meegroeit", steps: ["Bewaar maat, gewicht en kosten per order.", "Gebruik vaste verpakkingen en een controleerbare labelworkflow.", "Automatiseer wanneer handwerk of fouten zichtbaar oplopen.", "Evalueer tarieven, pickup en retouren bij iedere volumestap."]},
    ],
    sendwise: "Sendwise werkt volgens de website zonder abonnementskosten en losse vervoerderscontracten en kan starters toegang geven tot meerdere diensten. We helpen je een eenvoudige beginopzet te kiezen en later automatisering toe te voegen.",
    summary: "Kies als starter voor lage complexiteit en transparante kosten, maar leg data en processen meteen goed vast. Vergelijk platform en rechtstreekse routes op jouw echte pakketten.",
    faqs: [
      { question: "Heb ik als starter een vervoerderscontract nodig?", answer: "Niet altijd. Je kunt losse zakelijke diensten of een verzendplatform gebruiken, afhankelijk van vervoerder en gewenste service." },
      { question: "Is een verzendplatform altijd goedkoper?", answer: "Nee. Het kan volumevoordeel bieden, maar vergelijk totaalprijs, toeslagen en vaste kosten voor jouw profiel." },
      { question: "Wanneer heb ik een labelprinter nodig?", answer: "Zodra printen, knippen of plakken met een gewone printer merkbaar tijd kost of fouten veroorzaakt." },
      { question: "Moet ik retouren al vóór de eerste order regelen?", answer: "Ja. Een duidelijk retourbeleid is juridisch en voor klantvertrouwen belangrijk vanaf het moment dat je verkoopt." },
    ],
    sources: [
      { label: "Sendwise: oplossing voor webshops", href: "https://www.sendwise.nl/voor-webshops" },
      { label: "Europese Unie: regels voor online verkoop en retouren", href: "https://europa.eu/youreurope/citizens/consumers/shopping/returns/index_en.htm" },
    ],
    about: ["Startende webshop", "Eenmanszaak", "Pakketten verzenden", "Verzendplatform", "Retouren"], breadcrumb: "Verzenden als startende webshop",
  },

  "/kennisbank/webshop-starten-verzending-regelen": {
    title: "Webshop starten: verzending regelen in 5 stappen",
    seoTitle: "Webshop starten: verzending regelen in 5 stappen | Sendwise",
    description: "Regel verzending voor je nieuwe webshop in vijf stappen: pakketprofiel, verzendkosten, vervoerder, webshopkoppeling en retourproces.",
    excerpt: "Een praktisch vijfstappenplan voor verpakking, tarieven, vervoerder, automatisering en retouren vóór je eerste bestelling.",
    type: "Handleiding", category: "Starters", readTime: "± 8 min", publishedTime: "2026-08-18",
    image: "/kennisbank-verzendlabel.jpg", imageAlt: "Veel webshoporders klaar voor een ingericht verzendproces",
    quickAnswer: "Breng eerst je producten en verpakkingen in kaart, kies daarna je verzendkostenstrategie en vervoerder, koppel vervolgens orders en labels en richt tot slot retouren en klantcommunicatie in. Test het volledige proces met proeforders vóór je webshop live gaat.",
    introTitle: "Test de volledige route vóór je eerste klant", introEyebrow: "Van product tot retour",
    intro: ["Verzending raakt productmarge, checkout, klantenservice en retouren. Daarom hoort het niet pas na de websitebouw aan bod te komen.", "Gebruik de vijf stappen als minimale operationele checklist en voer minstens één proeforder per pakkettype en bestemming uit."],
    sections: [
      { id: "stappen-1-2", eyebrow: "Product en prijs", title: "Stap 1 en 2: pakketprofiel en verzendkosten", items: [
        { title: "1. Bepaal wat je verzendt", text: "Meet verzendklare maten, gewicht, waarde en kwetsbaarheid en kies passende verpakkingen." },
        { title: "2. Kies je kostenstrategie", text: "Bereken doorberekenen, gratis verzending of een drempel op basis van marge en orderwaarde." },
      ]},
      { id: "stappen-3-4", eyebrow: "Vervoerder en techniek", title: "Stap 3 en 4: kies en koppel", items: [
        { title: "3. Kies dienst en vervoerder", text: "Vergelijk totale kosten, bezorgopties, aanlevering, dekking en belangrijkste bestemmingen." },
        { title: "4. Koppel je webshop", text: "Laat orders doorstromen naar labels en tracking en richt een veilige standaarddienst in." },
      ]},
      { id: "stap-5", eyebrow: "Na de aankoop", title: "Stap 5: regel retouren en uitzonderingen", paragraphs: ["Publiceer retourvoorwaarden, kies binnenlandse en internationale routes en leg vast wie klantvragen en claims afhandelt.", "Test ook foutscenario’s: verkeerd adres, beschadiging, gemiste pickup, retour en ontbrekende scan." ]},
    ],
    sendwise: "Sendwise ondersteunt advies over vervoerders, koppelingen, labels, tracking en een retourportaal. Zo kun je de vijf onderdelen in één verzendproces samenbrengen zonder direct losse vervoerderscontracten te beheren.",
    summary: "Ken je zending, bereken je klanttarief, kies een passende dienst, automatiseer de orderstroom en regel retouren. Rond af met proeforders en foutscenario’s vóór livegang.",
    faqs: [
      { question: "Wanneer moet ik verzending regelen voor mijn webshop?", answer: "Vóór livegang, zodat tarieven, verpakking, checkoutbelofte en retourvoorwaarden kunnen worden getest." },
      { question: "Wat moet ik meten?", answer: "Meet de gesloten verpakking: lengte, breedte, hoogte en werkelijk gewicht." },
      { question: "Moet ik direct meerdere vervoerders kiezen?", answer: "Niet per se. Begin met een passende standaarddienst en leg een alternatief vast wanneer bestemming of pakketprofiel daarom vraagt." },
      { question: "Welke proeforders moet ik doen?", answer: "Test ieder belangrijk pakkettype, verzendland, trackingroute en minimaal één retour of foutscenario." },
    ],
    sources: [
      { label: "Sendwise: voor webshops", href: "https://www.sendwise.nl/voor-webshops" },
      { label: "PostNL: pakket verpakken en adresseren", href: "https://www.postnl.nl/versturen/pakket-versturen/hoe-verstuur-ik-een-pakket/pakket-adresseren-en-verpakken/" },
    ],
    about: ["Webshop starten", "Verzending regelen", "Vervoerder", "Webshopkoppeling", "Retourproces"], breadcrumb: "Webshop starten en verzending regelen",
  },

  "/kennisbank/goedkoopste-vervoerder-pakket": {
    title: "Met welke vervoerder verstuur je het goedkoopst een pakketje?",
    seoTitle: "Goedkoopste vervoerder voor een pakket | Sendwise",
    description: "Vergelijk de goedkoopste vervoerder per pakket op formaat, gewicht, bestemming, afleverwijze, volume, pickup, toeslagen en extra services.",
    excerpt: "Er is geen vaste goedkoopste vervoerder: vergelijk per pakketprofiel de totale prijs inclusief toeslagen, pickup en retouren.",
    type: "Blog", category: "Verzendkosten", readTime: "± 7 min", publishedTime: "2026-08-18",
    image: "/sendwise-hero-delivery-van.jpg", imageAlt: "Pakketten worden verzameld voor verzending via verschillende vervoerders",
    quickAnswer: "De goedkoopste vervoerder verschilt per pakket, bestemming, service en contract. Vergelijk niet alleen het basistarief, maar ook formaat- en gewichtscorrecties, brandstof- en piektoeslagen, pickup, retouren, dekking en foutkosten. Maak een prijsvergelijking op je eigen orderdata.",
    introTitle: "De goedkoopste keuze bestaat per verzendprofiel", introEyebrow: "Geen universele winnaar",
    intro: ["Een brievenbuszending, zwaar pakket en internationale retour vragen verschillende netwerken en tarieven. Eén ranglijst kan daardoor misleidend zijn.", "Ook volumevoordeel via een platform is profielafhankelijk. Het kan gunstig zijn, maar moet blijken uit de actuele totaalprijs van jouw zendingen."],
    sections: [
      { id: "factoren", eyebrow: "Meer dan het basistarief", title: "Welke factoren bepalen de prijs?", items: [
        { title: "Maat en gewicht", text: "Staffels, volumetrisch gewicht en afwijkende vormen kunnen de prijs wijzigen." },
        { title: "Bestemming", text: "Land, regio, eiland, afgelegen gebied en douane beïnvloeden tarief en service." },
        { title: "Afleverwijze", text: "Brievenbus, thuis, pakketpunt en zakelijke adressen hebben verschillende producten." },
        { title: "Extra diensten", text: "Verzekering, handtekening, tijdvak, leeftijdscheck en express kosten extra." },
      ]},
      { id: "pickup", eyebrow: "Effectieve kosten", title: "Neem aanlevering en volume mee", paragraphs: ["Pickupvoorwaarden en eventuele minimumvolumes verschillen per vervoerder en overeenkomst. Vraag naar frequentie, tijdvak, kosten en uitzonderingen.", "Zelf inleveren lijkt goedkoop, maar telt reistijd en operationele onderbreking mee. Een gecombineerde Sendwise-pickup kan afhankelijk van volume en locatie mogelijk zijn." ]},
      { id: "vergelijken", eyebrow: "Gebruik eigen data", title: "Zo vind je structureel de voordeligste route", steps: ["Groepeer historische orders op maat, gewicht, bestemming en service.", "Bereken per groep het volledige tarief inclusief correcties en retouren.", "Test één of twee passende alternatieven op bezorgkwaliteit en klantvragen.", "Automatiseer pas daarna de keuze met duidelijke verzendregels."]},
    ],
    sendwise: "Sendwise bundelt vervoerders en zendingen in één platform en kan scherpe tarieven bieden zonder losse contracten. Welke dienst werkelijk voordeligst is, bepalen we op basis van jouw pakketprofiel en actuele voorwaarden. Een gezamenlijke pickup is afhankelijk van volume en locatie.",
    summary: "Er is geen vervoerder die altijd het goedkoopst is. Vergelijk totale kosten per werkelijk pakketprofiel en neem pickup, toeslagen, retouren en bezorgkwaliteit mee.",
    faqs: [
      { question: "Welke vervoerder is het goedkoopst?", answer: "Dat verschilt per formaat, gewicht, bestemming, service en tariefafspraak. Vergelijk op eigen orderdata." },
      { question: "Is een pakketpunt altijd goedkoper dan thuisbezorging?", answer: "Niet altijd. Het verschil hangt af van vervoerder, dienst en overeenkomst." },
      { question: "Geeft een verzendplatform altijd lagere tarieven?", answer: "Niet gegarandeerd voor ieder profiel. Vergelijk de actuele totaalprijs en voorwaarden met rechtstreeks boeken." },
      { question: "Kan één pickup meerdere vervoerders meenemen?", answer: "Bij Sendwise kan dit afhankelijk van volume, locatie en operationele afspraken mogelijk zijn." },
    ],
    sources: [
      { label: "PostNL: zakelijke formaten en toeslagen", href: "https://www.postnl.nl/zakelijk/klantenservice/facturen/alles-over-facturen-en-kosten/" },
      { label: "DHL eCommerce: zakelijke afmetingen en gewichten", href: "https://www.dhlecommerce.nl/nl/zakelijk/support/verzenden/afmetingen-en-gewicht" },
      { label: "Sendwise: actuele indicatieve tarieven", href: "https://www.sendwise.nl/prijzen" },
    ],
    about: ["Goedkoopste vervoerder", "Verzendkosten", "Pakket verzenden", "Pickup", "Webshop"], breadcrumb: "Goedkoopste vervoerder",
  },
}
